/*
 * This file is generated by jOOQ.
*/
package swust.PdfVerify.pojo.po.mysql;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import swust.PdfVerify.pojo.po.mysql.tables.Doc;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Document extends SchemaImpl {

    private static final long serialVersionUID = -1208872837;

    /**
     * The reference instance of <code>document</code>
     */
    public static final Document DOCUMENT = new Document();

    /**
     * The table <code>document.doc</code>.
     */
    public final Doc DOC = swust.PdfVerify.pojo.po.mysql.tables.Doc.DOC;

    /**
     * No further instances allowed
     */
    private Document() {
        super("document", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Doc.DOC);
    }
}
