/*
 * This file is generated by jOOQ.
*/
package swust.PdfVerify.pojo.po.mysql;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import swust.PdfVerify.pojo.po.mysql.tables.Doc;


/**
 * A class modelling indexes of tables of the <code>document</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DOC_PRIMARY = Indexes0.DOC_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DOC_PRIMARY = Internal.createIndex("PRIMARY", Doc.DOC, new OrderField[] { Doc.DOC.ID }, true);
    }
}
