/*
 * This file is generated by jOOQ.
*/
package swust.PdfVerify.pojo.po.mysql;


import javax.annotation.Generated;

import swust.PdfVerify.pojo.po.mysql.tables.Doc;


/**
 * Convenience access to all tables in document
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>document.doc</code>.
     */
    public static final Doc DOC = swust.PdfVerify.pojo.po.mysql.tables.Doc.DOC;
}
