/*
 * This file is generated by jOOQ.
*/
package swust.PdfVerify.pojo.po.mysql.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Doc implements Serializable {

    private static final long serialVersionUID = -479752487;

    private Long   id;
    private String docWebPath;
    private Long   docId;
    private String docLocalPath;

    public Doc() {}

    public Doc(Doc value) {
        this.id = value.id;
        this.docWebPath = value.docWebPath;
        this.docId = value.docId;
        this.docLocalPath = value.docLocalPath;
    }

    public Doc(
        Long   id,
        String docWebPath,
        Long   docId,
        String docLocalPath
    ) {
        this.id = id;
        this.docWebPath = docWebPath;
        this.docId = docId;
        this.docLocalPath = docLocalPath;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDocWebPath() {
        return this.docWebPath;
    }

    public void setDocWebPath(String docWebPath) {
        this.docWebPath = docWebPath;
    }

    public Long getDocId() {
        return this.docId;
    }

    public void setDocId(Long docId) {
        this.docId = docId;
    }

    public String getDocLocalPath() {
        return this.docLocalPath;
    }

    public void setDocLocalPath(String docLocalPath) {
        this.docLocalPath = docLocalPath;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Doc (");

        sb.append(id);
        sb.append(", ").append(docWebPath);
        sb.append(", ").append(docId);
        sb.append(", ").append(docLocalPath);

        sb.append(")");
        return sb.toString();
    }
}
